identifier_name:
  min_length: 2
  excluded: 
   - x
   - y
   - T
type_name:
  allowed_symbols:
    - "_"
  max_length: 100
line_length: 120
file_length: 800
type_body_length:
  warning: 500
number_separator:
  minimum_length: 5
trailing_comma:
  mandatory_comma: true
function_body_length:
  warning: 120
  error: 150
disabled_rules:
  - nesting
  - redundant_nil_coalescing
  - conditional_returns_on_newline
  - type_name
  - attributes
  - comment_spacing
opt_in_rules: # these settings are inherited from another project - adjust as needed
 - closure_spacing
 - conditional_returns_on_newline
 - empty_count
 - explicit_init
 - overridden_super_call
 - redundant_nil_coalescing
 - nimble_operator
 - closure_end_indentation
 - first_where
 - attributes
 - operator_usage_whitespace
 - prohibited_super_call
 - number_separator
 - object_literal
 - fatal_error_message
excluded:
  - .build

custom_rules:
  leading_whitespace:
    name: Tabs
    message: Use tab indentation
    regex: ^\t* +\t*\S
    severity: error
