identifier_name:
  min_length: 2
  excluded: 
   - x
   - y
   - T
type_name:
  allowed_symbols:
    - "_"
  max_length: 100
line_length: 120
file_length: 800
type_body_length:
  warning: 500
number_separator:
  minimum_length: 5
trailing_comma:
  mandatory_comma: true
function_body_length:
  warning: 120
  error: 150
opening_brace:
  ignore_multiline_statement_conditions: true
attributes:
  always_on_same_line: ["@IBAction", "@NSManaged", "@Test"]
  always_on_line_above: ["@NHActor"]

disabled_rules:
  - nesting
  - closing_brace
opt_in_rules:
  - number_separator
  - closure_spacing
  - overridden_super_call
  - attributes
  - fatal_error_message
  - empty_count
  - redundant_nil_coalescing
  - first_where
  - operator_usage_whitespace
  - prohibited_super_call
excluded:
  - .build

custom_rules:
  leading_whitespace:
    name: Tabs
    message: Use tab indentation
    regex: ^\t* +\t*\S
    severity: error
